apiVersion: v1
kind: Pod
metadata:
  name: qualys
spec:

  restartPolicy: Always

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: qualys
    image: image_name:latest
    resources:
        limits:
          memory: 2Gi
        requests:
          cpu: 150m
          memory: 2Gi