apiVersion: v1
kind: Service
metadata:
  name: qualys
  namespace: cpe-tvm-services
  labels:
    app: qualys
spec:
  ports:
    - name: 5002-tcp
      protocol: TCP
      port: 5002
      targetPort: 5002
  selector:
    app: qualys
    deploymentconfig: qualys
  sessionAffinity: None
status:
  loadBalancer: {}