apiVersion: v1
kind: DeploymentConfig
metadata:
  name: sonar-scanner
  namespace: namespace_name
  labels:
    app: sonar-scanner
spec:
  replicas: 1
  test: false
  selector:
    app: sonar-scanner
    deploymentconfig: sonar-scanner
  template:
    metadata:
      labels:
        app: sonar-scanner
        deploymentconfig: sonar-scanner
    spec:
      containers:
        - name: sonar-scanner-release
          image: >-
            image_name:latest
          ports:
            - containerPort: 5002
              protocol: TCP
          env:
            - name: MIS_SQS_SECRET
              valueFrom:
                secretKeyRef:
                  name: mis-sqs-secret
                  key: token
            - name: MIS_SQS_KEY
              valueFrom:
                secretKeyRef:
                  name: mis-sqs-key
                  key: token
          resources: 
            limits:
              memory: 2Gi
            requests:
              memory: 2Gi
          imagePullPolicy: Always
      restartPolicy: Always
      securityContext: {}
