apiVersion: v1
kind: Service
metadata:
  name: sonar-scanner
  namespace: namespace_name
  labels:
    app: sonar-scanner
spec:
  ports:
    - name: 5002-tcp
      protocol: TCP
      port: 5002
      targetPort: 5002
  selector:
    app: sonar-scanner
    deploymentconfig: sonar-scanner
  sessionAffinity: None
status:
  loadBalancer: {}
